import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import p from './src/profile.mjs';
import { educationDetails, experience, interestDetails, teachingExperience } from './src/details.mjs';
import { systemsDiagram, adaptationDiagram } from './src/diagrams.mjs';
import { adeqResults, coastalResults } from './src/research-results.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sci=v=>e(v).replaceAll('Spartina alterniflora','<i>Spartina alterniflora</i>');
const cv='/assets/Jiangzi-Chen-CV.pdf', mail=`mailto:${p.email}`;
const pages=[['about','/','About'],['research','/research/','Research'],['publications','/publications/','Publications'],['education','/education/','Education'],['contact','/contact/','Contact']];
const link=(url,label,cls='text-link')=>`<a class="${cls}" href="${url}">${label} <span aria-hidden="true">›</span></a>`;
const list=items=>`<ul class="contribution-list">${items.map(t=>`<li>${sci(t)}</li>`).join('')}</ul>`;
const heading=(k,t,d)=>`<section class="page-heading"><p class="eyebrow">${k}</p><h1>${t}</h1><p class="page-intro">${d}</p></section>`;
const endnote=()=>`<aside class="endnote"><p>Full project history and additional background are available in my CV.</p>${link(cv,'View CV')}</aside>`;
const nav=current=>`<header class="site-header"><div class="header-inner"><a class="brand" href="/">Jiangzi Chen<span class="accent">.</span></a><nav aria-label="Main navigation">${pages.map(([id,url,name])=>`<a href="${url}"${id===current?' aria-current="page"':''}>${name}</a>`).join('')}</nav><a class="header-cv" href="${cv}" aria-label="Curriculum vitae, PDF">CV ↗</a></div></header>`;
const footer=()=>`<footer class="site-footer"><div class="footer-inner"><div><a class="footer-name" href="/">Jiangzi Chen</a><p>M.S. student · Arizona State University</p></div><div class="footer-links"><a href="${mail}">Email</a><a href="${cv}">CV (PDF)</a><a href="#top">Back to top ↑</a></div></div></footer>`;
const portrait=()=>p.photo?`<figure class="portrait"><img src="${e(p.photo)}" alt="Portrait of Jiangzi Chen" width="1280" height="1920"></figure>`:'<figure class="portrait portrait-placeholder" role="img" aria-label="Reserved space for Jiangzi Chen’s portrait"><span class="portrait-monogram" aria-hidden="true">JC</span><figcaption>Portrait to come</figcaption></figure>';

function about(){return `<div class="page-shell"><section class="profile-hero">${portrait()}<div class="profile-intro"><p class="eyebrow">GEOSPATIAL &amp; ENVIRONMENTAL RESEARCH</p><h1>Jiangzi Chen<span class="accent">.</span></h1><p class="profile-role">M.S. student<br><span>Arizona State University</span></p><p class="hero-bio">${e(p.biography[0])}</p><div class="hero-actions"><a class="button" href="${cv}">Curriculum vitae <span>PDF</span></a>${link('/research/','Explore my research')}</div></div></section>
  <section class="work-story section-spacing" aria-labelledby="work-title"><div class="story-intro"><div><p class="eyebrow">ABOUT MY WORK</p><h2 id="work-title">People. Water. <br>A changing planet.</h2></div><div class="prose"><p class="story-lead">I want to understand the dynamic feedbacks between human activities and the hydrologic cycle—and what they mean for the places we live.</p><p>How do changes in land use and water management reshape environmental conditions? How do changes in water availability, quality, and risk influence our choices? These questions connect my interests in human impacts, ecological resilience, and adaptation.</p><p>My undergraduate work on coastal ecological resilience and land-use change examined how human pressures relate to ecosystem conditions. At ASU, my ongoing ADEQ project with Ruijie Zeng focuses on identifying potentially unpermitted on-site wastewater facilities in Arizona. Across these settings, I use spatial evidence to examine the relationship between people and their environment.</p></div></div>${systemsDiagram()}<div class="story-links">${link('/research/','Follow the research story')}${link('/education/','Education &amp; experience')}</div></section>
  <section class="interests-section section-spacing"><div class="section-title"><p class="eyebrow">RESEARCH INTERESTS</p><h2>Questions that connect my work.</h2></div><div class="interest-grid">${interestDetails.map(([title,text],i)=>`<article class="interest-card"><span class="card-number">0${i+1}</span><h3>${e(title)}</h3><p>${e(text)}</p></article>`).join('')}</div></section></div>`;}

function research(){return `<div class="page-shell research-story">
  <section class="page-heading research-hero"><p class="eyebrow">RESEARCH · HUMAN–ENVIRONMENT RELATIONSHIPS</p><h1>The future <br>we hope for<span class="accent">.</span></h1><p class="page-intro">Understanding how we shape our environment—and how a changing environment shapes our lives.</p></section>
  ${adaptationDiagram()}
  <section class="research-perspective"><h2>From understanding change <br>to informing adaptation.</h2><div class="prose"><p>Climate change is reshaping the conditions in which people and ecosystems depend on water. At the same time, urbanization, land-use change, and water management alter the movement and quality of water. These processes connect the atmosphere, hydrosphere, lithosphere, and biosphere, with consequences for communities and ecosystems.</p><p>My research interests center on this two-way relationship. I want to investigate how human activities affect the hydrologic cycle and how environmental feedbacks can inform adaptation. My work so far approaches this broader goal through coastal resilience assessment, land-use and habitat modeling, and the spatial identification of wastewater facilities.</p></div></section>
  <div class="featured-heading"><p class="eyebrow">TWO PERSPECTIVES ON THE SAME QUESTION</p><h2>From coastal landscapes <br>to the water systems we build.</h2><nav aria-label="Featured research"><a href="#coastal-resilience">01 · Coastal resilience <span aria-hidden="true">↓</span></a><a href="#wastewater">02 · ADEQ project <span aria-hidden="true">↓</span></a></nav></div>
  <article class="featured-study" id="coastal-resilience"><div class="study-title"><span class="study-number">01</span><div><p class="eyebrow">COASTAL ECOLOGICAL RESILIENCE · PUBLISHED RESEARCH</p><h2>How resilient are our <br>coastal landscapes?</h2><p class="study-meta">China’s coastal zone · Feb 2024 – Jul 2025<br>Nanjing University of Information Science and Technology<br>Supervisor: Chengyi Zhao</p></div></div><p class="study-opening">Coastal landscapes bring human development and ecological processes into close contact. This project asked how ecological resilience varies across China’s coastal zone, how it changes over time, and how its future may differ under alternative climate and development scenarios.</p>
  ${coastalResults()}
  <div class="study-detail-grid"><section><h3>Reading the landscape</h3><p>The study used the Pressure–State–Response (PSR) framework to assess ecological resilience at the pixel scale. It connected indicators of environmental pressure, ecosystem condition, and responses, then examined spatial and temporal patterns and future trajectories under SSP–RCP scenarios.</p><p class="term-note">SSP–RCP scenarios combine socioeconomic pathways with climate forcing pathways.</p></section><section><h3>My contribution</h3><p>I contributed data analysis to the resilience assessment and scenario comparisons. The work connected spatial patterns with questions about how human and environmental pressures may shape coastal futures.</p><p>I am a coauthor of the resulting article, published in <i>Land</i> in 2024.</p></section></div>
  <aside class="study-publication"><div><span class="eyebrow">PUBLISHED IN LAND · 2024</span><h3>${e(p.publications[0].title)}</h3><p>13(12), 2130 · DOI: 10.3390/land13122130</p></div>${link(p.publications[0].url,'Read the paper ↗')}</aside>
  <section class="related-study" id="habitat-quality"><p class="eyebrow">A CONNECTED UNDERGRADUATE PROJECT</p><h3>Land-use change, habitat quality, and future choices.</h3><p>In a separate project, I led work coupling PLUS and InVEST to examine coastal land-use patterns and habitat quality from 2020 to 2050 under SSP126, SSP245, and SSP585. I assessed drivers of habitat-quality change and the contribution of land-cover changes to degradation.</p><p>Together, these experiences shaped my interest in how spatial assessment and scenario analysis can inform land-use planning and adaptation.</p></section></article>
  <article class="featured-study" id="wastewater"><div class="study-title"><span class="study-number">02</span><div><p class="eyebrow">ADEQ PROJECT · WATER &amp; ENVIRONMENTAL HEALTH</p><h2>Making wastewater <br>infrastructure more visible.</h2><p class="study-meta">Arizona, United States · Jan 2026 – Present · Ongoing<br>Arizona State University<br>Supervisor: Ruijie Zeng</p></div></div><p class="study-opening">The relationship between people and water is also built into everyday infrastructure. My current ADEQ project asks how spatial analysis can help locate on-site wastewater treatment facilities, including potentially unpermitted facilities in rural Arizona.</p>
  ${adeqResults()}
  <div class="study-detail-grid"><section><h3>Building a spatial picture</h3><p>I use GIS to analyze potential on-site wastewater locations across Arizona. The current study combines county parcels and buildings, sewer and public-water service areas, community characteristics, and available wastewater records in a county-specific identification workflow.</p><p>Candidate identifiers are normalized and matched within counties. Permit-supported candidates are retained; other records with verified explicit vacant-land labels are screened out. The resulting inventory provides a basis for targeted record review and further investigation.</p></section><section><h3>Connecting infrastructure and environment</h3><p>This work extends my interest in human–environment relationships from coastal land use to the water systems serving communities. Better information about wastewater infrastructure can support environmental health assessment and help identify where closer attention may be useful.</p><p>The project is ongoing; my current contribution centers on spatial analysis and facility identification.</p></section></div>
  <div class="study-takeaway"><span class="eyebrow">THE CONNECTING THREAD</span><p>From changes in coastal land cover to wastewater infrastructure, I use spatial evidence to understand how human activity intersects with environmental systems.</p></div></article>${endnote()}</div>`;}

function publications(){const a=p.publications[0],b=p.publications[1];return `<div class="page-shell publications-page">${heading('PUBLICATIONS','Research in writing.','Published work and a submitted manuscript on coastal ecological resilience and wetland dynamics.')}<section class="publication-section"><h2 class="section-label">Published article <span>01</span></h2><article class="publication-card"><div class="publication-topline"><span class="status-badge">Published</span><span>2024 · Land</span></div><h3><a href="${a.url}">${e(a.title)}</a></h3><p class="authors">${a.authors.map(n=>n===p.name?`<strong>${e(n)}</strong>`:e(n)).join(', ')}</p><p class="journal"><i>Land</i>, 13(12), 2130</p><div class="publication-details"><div><h4>Research overview</h4><p>The study applies the Pressure–State–Response framework to assess ecological resilience at the pixel scale across China’s coastal zone. It examines spatial and temporal changes and compares projected resilience under different climate and development scenarios.</p></div><div><h4>My contribution</h4><p>Data analysis. I am a coauthor of the published article.</p><p>The related project was supervised by Chengyi Zhao at Nanjing University of Information Science and Technology.</p></div></div><div class="publication-actions"><a class="button" href="${a.url}">Read the article ↗</a><span class="doi">DOI: 10.3390/land13122130</span></div></article></section><section class="publication-section"><h2 class="section-label">Submitted manuscript <span>01</span></h2><article class="publication-card manuscript-card"><div class="publication-topline"><span class="status-badge neutral">Submitted</span></div><h3>${e(b.title)}</h3><div class="publication-details"><div><h4>Research focus</h4><p>The associated project investigates relationships between <i>Spartina alterniflora</i> expansion and tidal creek evolution in Yellow Sea mudflats, including the Yancheng Red-crowned Crane Reserve.</p></div><div><h4>Related research experience</h4><p>My work included high-resolution remote sensing, vegetation monitoring, and analysis of relationships between vegetation distribution and tidal creek geometry.</p>${link(cv,'View full research history in my CV')}</div></div></article></section></div>`;}

function education(){const t=teachingExperience;return `<div class="page-shell education-page"><header class="education-heading"><p class="eyebrow">EDUCATION &amp; EXPERIENCE</p><h1 class="section-label">Education</h1></header><section aria-label="Education history"><div class="degree-list">${p.education.map((d,i)=>`<article class="degree-card"><div class="degree-year"><span>${i===0?'2025—':'2021—2025'}</span><p>${e(d.period)}</p></div><div class="degree-content"><p class="eyebrow">${i===0?'MASTER OF SCIENCE · IN PROGRESS':'BACHELOR OF SCIENCE'}</p><h3>${e(d.institution)}</h3><p class="degree-title">${e(d.degree)}</p><p>${e(educationDetails[i])}</p></div></article>`).join('')}</div></section><section class="teaching-section section-spacing" aria-labelledby="teaching-title"><h2 class="section-label" id="teaching-title">Teaching experience</h2><article class="experience-card teaching-card"><div class="experience-meta"><p>${e(t.period)}</p></div><div><h3>${e(t.role)} · ${e(t.course)}</h3><p class="experience-context">${e(t.institution)}</p>${list(t.points)}</div></article></section><section class="experience-section section-spacing"><div class="section-title"><p class="eyebrow">APPLIED EXPERIENCE</p><h2>Working beyond the classroom.</h2></div>${experience.map(d=>`<article class="experience-card"><div class="experience-meta"><p>${e(d.period)}</p><p>${e(d.role)}</p></div><div><h3>${e(d.organization)}</h3><p class="experience-context">${e(d.context)}</p>${list(d.points)}</div></article>`).join('')}</section><section class="toolkit section-spacing"><div><p class="eyebrow">RESEARCH TOOLKIT</p><h2>Tools I work with.</h2><p>Software used across my spatial analysis, remote sensing, and environmental modeling work.</p></div><ul class="tool-list">${p.skills.map(t=>`<li>${e(t)}</li>`).join('')}</ul></section>${endnote()}</div>`;}

function contact(){return `<div class="page-shell contact-page">${heading('CONTACT','Let’s connect.','For questions about my research and academic work, you can reach me by email.')}<section class="contact-primary"><p class="eyebrow">EMAIL</p><a class="email-link" href="${mail}">${e(p.email)} <span aria-hidden="true">↗</span></a><p>Jiangzi Chen · Arizona State University</p></section><div class="contact-grid"><section class="contact-card"><p class="eyebrow">ACADEMIC AFFILIATION</p><h2>Arizona State University</h2><p>M.S. student in Civil, Environmental and Sustainable Engineering</p><p class="small-muted">August 2025 – Present</p>${link('/education/','Education &amp; experience')}</section><section class="contact-card"><p class="eyebrow">CURRICULUM VITAE</p><h2>My background, in detail.</h2><p>Education, research projects, publications, teaching, professional experience, and technical skills.</p><a class="button secondary" href="${cv}">View CV <span>PDF · 2 pages</span></a></section></div></div>`;}

const renderers={about,research,publications,education,contact};
const descriptions={about:'Jiangzi Chen, a master’s student at Arizona State University, studies environmental change using GIS, remote sensing, and environmental modeling.',research:'The future we hope for: Jiangzi Chen’s research interests in human–water feedbacks, coastal resilience, wastewater infrastructure, and adaptation.',publications:'Published work and a submitted manuscript by Jiangzi Chen on coastal ecological resilience and tidal creek dynamics.',education:'Jiangzi Chen’s education at Arizona State University and NUIST, CEE 441 teaching assistantship, professional experience, and research tools.',contact:'Contact Jiangzi Chen at Arizona State University and download the academic CV.'};
const icon="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='8' fill='%231d1d1f'/%3E%3Cpath d='M20 7v13c0 7-11 7-11 0M14 7h11' fill='none' stroke='white' stroke-width='3'/%3E%3C/svg%3E";
for(const [id,url,label] of pages){const title=id==='about'?'Jiangzi Chen — Academic Profile':`${label} — Jiangzi Chen`;const html=`<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f5f5f7"><title>${e(title)}</title><meta name="description" content="${e(descriptions[id])}"><link rel="icon" type="image/svg+xml" href="${icon}"><link rel="stylesheet" href="/styles.css"></head><body id="top"><a class="skip-link" href="#main">Skip to content</a>${nav(id)}<main id="main">${renderers[id]()}</main>${footer()}</body></html>\n`;const directory=path.join(root,id==='about'?'':id);mkdirSync(directory,{recursive:true});writeFileSync(path.join(directory,'index.html'),html,'utf8');}
console.log('Generated five static academic profile pages.');

